### PR TITLE
Open Menu/Pauses and unpause game using escape key.

### PR DESCRIPTION
**Pull request by wviana**
Please fell free to ask for any clarification.

Also removed  `_in_game_menu_is_open` boolean as it was not necessary as `_in_game_menu_dialog` already represents if the menu is visible or not.

Loved it BTW :heart:

### CODE REVIEW

**Comment by plbrault** [comment]
That's a great idea! I will just need to confirm how it behaves on itch.io as the Escape key is usually used to leave fullscreen mode.

**Comment by plbrault** [comment]
After testing, it unfortunately does conflict with itch.io's handling of the Escape key in fullscreen. The result is that fullscreen mode is exited, but the menu does not open. I'm not sure what the solution could be.

Also, the PR seems to introduce a glitch where a rectangle appears for a fraction of a second in the top-left corner of the screen when opening the menu. I'm not sure why.

**Comment by wviana** [comment]
Hi @plbrault,
Just updated this branch. 
I've created a account in itch.io. Uploaded my version and tested it. When on fullscreen it closes fullscreen.
When not in fullscreen it pauses the game.

I it's acceptable behavior .

**Comment by plbrault** [comment]
Glitch mentioned in previous comment is still present.

**Comment by plbrault** [comment]
@wviana I closed your PR by accident and I seem to even have erased changes from your fork, but I recreated the same PR here: https://github.com/plbrault/youre-the-os/pull/90

I managed to fix the glitch

**Pull request closed without merging**
