### PR TITLE
Implement automation mechanism

### PR DESCRIPTION
**Pull request by Wiguwbe**
An external script can be used to automate the scheduling.

An event manager receives events from processes, pages and IO queue, and dispatches them to the external script.

The external script then processes the events and returns a list of actionable events (simulating clicks).

The game scene dispatches the received events to the respective receivers.

Main changes are:
- event manager;
- changes to provide events to event manager;
- compile and execute an external script;
- _on_click/_onClick is now public;
- game's scene dispatches events from script before calling the update function

An example automated script is provided, mostly to explain the exposed API, it has a (not so) simple example implementation.

### CODE REVIEW

**Comment by Wiguwbe** [comment]
To run, provide a python script as argument (I shall update the Readme)

**Comment by wviana** [comment]
Maybe we could create another PR just removing those unnecessary white spaces. So it will make cleaner these commits.
This time not only in files you've touched, but the entire project.

**Comment by Wiguwbe** [comment]
I did notice that a lot of whitespace was trimmed, just haven't actually looked at the diff here

It should be easy to make

**Comment by plbrault** [comment]
Hey! This looks amazing! It will take me a little while to review though and I will be quite busy over the next few days, so I will get back to you as soon as I can.

**Pull request closed without merging**
